[project]
name = "test-streamlit-labeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.53",
    "rich>=14.2.0",
    "streamlit>=1.50.0",
]
